In [14]:
import pandas as pd
import pyarrow.parquet as pq
from sqlalchemy import create_engine

In [15]:
# Step 1: Read the Parquet file
trips = pq.read_table('yellow_tripdata_2024-01.parquet')
trips = trips.to_pandas()
trips

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,2,2024-01-01 00:57:55,2024-01-01 01:17:43,1.0,1.72,1.0,N,186,79,2,17.70,1.00,0.5,0.00,0.00,1.0,22.70,2.5,0.0
1,1,2024-01-01 00:03:00,2024-01-01 00:09:36,1.0,1.80,1.0,N,140,236,1,10.00,3.50,0.5,3.75,0.00,1.0,18.75,2.5,0.0
2,1,2024-01-01 00:17:06,2024-01-01 00:35:01,1.0,4.70,1.0,N,236,79,1,23.30,3.50,0.5,3.00,0.00,1.0,31.30,2.5,0.0
3,1,2024-01-01 00:36:38,2024-01-01 00:44:56,1.0,1.40,1.0,N,79,211,1,10.00,3.50,0.5,2.00,0.00,1.0,17.00,2.5,0.0
4,1,2024-01-01 00:46:51,2024-01-01 00:52:57,1.0,0.80,1.0,N,211,148,1,7.90,3.50,0.5,3.20,0.00,1.0,16.10,2.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2964619,2,2024-01-31 23:45:59,2024-01-31 23:54:36,NaN,3.18,NaN,None,107,263,0,15.77,0.00,0.5,2.00,0.00,1.0,21.77,NaN,NaN
2964620,1,2024-01-31 23:13:07,2024-01-31 23:27:52,NaN,4.00,NaN,None,114,236,0,18.40,1.00,0.5,2.34,0.00,1.0,25.74,NaN,NaN
2964621,2,2024-01-31 23:19:00,2024-01-31 23:38:00,NaN,3.33,NaN,None,211,25,0,19.97,0.00,0.5,0.00,0.00,1.0,23.97,NaN,NaN
2964622,2,2024-01-31 23:07:23,2024-01-31 23:25:14,NaN,3.06,NaN,None,107,13,0,23.88,0.00,0.5,5.58,0.00,1.0,33.46,NaN,NaN
2964623,1,2024-01-31 23:58:25,2024-02-01 00:13:30,NaN,8.10,NaN,None,138,75,0,32.40,7.75,0.5,7.29,6.94,1.0,55.88,NaN,NaN

In [16]:
# Step 2: Create the SQLAlchemy engine
db_url = 'postgresql://root:root@localhost:5432/ny_taxi'
engine = create_engine(db_url)

In [17]:
# Step 3: Insert data into the PostgreSQL table in chunks with progress tracking
chunk_size = 10000  # Adjust the chunk size as needed
num_chunks = (len(trips) - 1) // chunk_size + 1  # Calculate the number of chunks

for i, chunk in enumerate(range(0, len(trips), chunk_size)):
    trips[chunk:chunk + chunk_size].to_sql('yellow_taxi_data', engine, if_exists='replace', index=False)
    print(f'Inserted chunk {i+1} of {num_chunks}')

Inserted chunk 1 of 297
Inserted chunk 2 of 297
Inserted chunk 3 of 297
Inserted chunk 4 of 297
Inserted chunk 5 of 297
Inserted chunk 6 of 297
Inserted chunk 7 of 297
Inserted chunk 8 of 297
Inserted chunk 9 of 297
Inserted chunk 10 of 297
Inserted chunk 11 of 297
Inserted chunk 12 of 297
Inserted chunk 13 of 297
Inserted chunk 14 of 297
Inserted chunk 15 of 297
Inserted chunk 16 of 297
Inserted chunk 17 of 297
Inserted chunk 18 of 297
Inserted chunk 19 of 297
Inserted chunk 20 of 297
Inserted chunk 21 of 297
Inserted chunk 22 of 297
Inserted chunk 23 of 297
Inserted chunk 24 of 297
Inserted chunk 25 of 297
Inserted chunk 26 of 297
Inserted chunk 27 of 297
Inserted chunk 28 of 297
Inserted chunk 29 of 297
Inserted chunk 30 of 297
Inserted chunk 31 of 297
Inserted chunk 32 of 297
Inserted chunk 33 of 297
Inserted chunk 34 of 297
Inserted chunk 35 of 297
Inserted chunk 36 of 297
Inserted chunk 37 of 297
Inserted chunk 38 of 297
Inserted chunk 39 of 297
Inserted chunk 40 of 297
Inserted chunk 41 of 297
Inserted chunk 42 of 297
Inserted chunk 43 of 297
Inserted chunk 44 of 297
Inserted chunk 45 of 297
Inserted chunk 46 of 297
Inserted chunk 47 of 297
Inserted chunk 48 of 297
Inserted chunk 49 of 297
Inserted chunk 50 of 297
Inserted chunk 51 of 297
Inserted chunk 52 of 297
Inserted chunk 53 of 297
Inserted chunk 54 of 297
Inserted chunk 55 of 297
Inserted chunk 56 of 297
Inserted chunk 57 of 297
Inserted chunk 58 of 297
Inserted chunk 59 of 297
Inserted chunk 60 of 297
Inserted chunk 61 of 297
Inserted chunk 62 of 297
Inserted chunk 63 of 297
Inserted chunk 64 of 297
Inserted chunk 65 of 297
Inserted chunk 66 of 297
Inserted chunk 67 of 297
Inserted chunk 68 of 297
Inserted chunk 69 of 297
Inserted chunk 70 of 297
Inserted chunk 71 of 297
Inserted chunk 72 of 297
Inserted chunk 73 of 297
Inserted chunk 74 of 297
Inserted chunk 75 of 297
Inserted chunk 76 of 297
Inserted chunk 77 of 297
Inserted chunk 78 of 297
Inserted chunk 79 of 297
Inserted chunk 80 of 297
Inserted chunk 81 of 297
Inserted chunk 82 of 297
Inserted chunk 83 of 297
Inserted chunk 84 of 297
Inserted chunk 85 of 297
Inserted chunk 86 of 297
Inserted chunk 87 of 297
Inserted chunk 88 of 297
Inserted chunk 89 of 297
Inserted chunk 90 of 297
Inserted chunk 91 of 297
Inserted chunk 92 of 297
Inserted chunk 93 of 297
Inserted chunk 94 of 297
Inserted chunk 95 of 297
Inserted chunk 96 of 297
Inserted chunk 97 of 297
Inserted chunk 98 of 297
Inserted chunk 99 of 297
Inserted chunk 100 of 297
Inserted chunk 101 of 297
Inserted chunk 102 of 297
Inserted chunk 103 of 297
Inserted chunk 104 of 297
Inserted chunk 105 of 297
Inserted chunk 106 of 297
Inserted chunk 107 of 297
Inserted chunk 108 of 297
Inserted chunk 109 of 297
Inserted chunk 110 of 297
Inserted chunk 111 of 297
Inserted chunk 112 of 297
Inserted chunk 113 of 297
Inserted chunk 114 of 297
Inserted chunk 115 of 297
Inserted chunk 116 of 297
Inserted chunk 117 of 297
Inserted chunk 118 of 297
Inserted chunk 119 of 297
Inserted chunk 120 of 297
Inserted chunk 121 of 297
Inserted chunk 122 of 297
Inserted chunk 123 of 297
Inserted chunk 124 of 297
Inserted chunk 125 of 297
Inserted chunk 126 of 297
Inserted chunk 127 of 297
Inserted chunk 128 of 297
Inserted chunk 129 of 297
Inserted chunk 130 of 297
Inserted chunk 131 of 297
Inserted chunk 132 of 297
Inserted chunk 133 of 297
Inserted chunk 134 of 297
Inserted chunk 135 of 297
Inserted chunk 136 of 297
Inserted chunk 137 of 297
Inserted chunk 138 of 297
Inserted chunk 139 of 297
Inserted chunk 140 of 297
Inserted chunk 141 of 297
Inserted chunk 142 of 297
Inserted chunk 143 of 297
Inserted chunk 144 of 297
Inserted chunk 145 of 297
Inserted chunk 146 of 297
Inserted chunk 147 of 297
Inserted chunk 148 of 297
Inserted chunk 149 of 297
Inserted chunk 150 of 297
Inserted chunk 151 of 297
Inserted chunk 152 of 297
Inserted chunk 153 of 297
Inserted chunk 154 of 297
Inserted chunk 155 of 297
Inserted chunk 156 of 297
Inserted chunk 157 of 297
Inserted chunk 158 of 297
Inserted chunk 159 of 297
Inserted chunk 160 of 297
Inserted chunk 161 of 297
Inserted chunk 162 of 297
Inserted chunk 163 of 297
Inserted chunk 164 of 297
Inserted chunk 165 of 297
Inserted chunk 166 of 297
Inserted chunk 167 of 297
Inserted chunk 168 of 297
Inserted chunk 169 of 297
Inserted chunk 170 of 297
Inserted chunk 171 of 297
Inserted chunk 172 of 297
Inserted chunk 173 of 297
Inserted chunk 174 of 297
Inserted chunk 175 of 297
Inserted chunk 176 of 297
Inserted chunk 177 of 297
Inserted chunk 178 of 297
Inserted chunk 179 of 297
Inserted chunk 180 of 297
Inserted chunk 181 of 297
Inserted chunk 182 of 297
Inserted chunk 183 of 297
Inserted chunk 184 of 297
Inserted chunk 185 of 297
Inserted chunk 186 of 297
Inserted chunk 187 of 297
Inserted chunk 188 of 297
Inserted chunk 189 of 297
Inserted chunk 190 of 297
Inserted chunk 191 of 297
Inserted chunk 192 of 297
Inserted chunk 193 of 297
Inserted chunk 194 of 297
Inserted chunk 195 of 297
Inserted chunk 196 of 297
Inserted chunk 197 of 297
Inserted chunk 198 of 297
Inserted chunk 199 of 297
Inserted chunk 200 of 297
Inserted chunk 201 of 297
Inserted chunk 202 of 297
Inserted chunk 203 of 297
Inserted chunk 204 of 297
Inserted chunk 205 of 297
Inserted chunk 206 of 297
Inserted chunk 207 of 297
Inserted chunk 208 of 297
Inserted chunk 209 of 297
Inserted chunk 210 of 297
Inserted chunk 211 of 297
Inserted chunk 212 of 297
Inserted chunk 213 of 297
Inserted chunk 214 of 297
Inserted chunk 215 of 297
Inserted chunk 216 of 297
Inserted chunk 217 of 297
Inserted chunk 218 of 297
Inserted chunk 219 of 297
Inserted chunk 220 of 297
Inserted chunk 221 of 297
Inserted chunk 222 of 297
Inserted chunk 223 of 297
Inserted chunk 224 of 297
Inserted chunk 225 of 297
Inserted chunk 226 of 297
Inserted chunk 227 of 297
Inserted chunk 228 of 297
Inserted chunk 229 of 297
Inserted chunk 230 of 297
Inserted chunk 231 of 297
Inserted chunk 232 of 297
Inserted chunk 233 of 297
Inserted chunk 234 of 297
Inserted chunk 235 of 297
Inserted chunk 236 of 297
Inserted chunk 237 of 297
Inserted chunk 238 of 297
Inserted chunk 239 of 297
Inserted chunk 240 of 297
Inserted chunk 241 of 297
Inserted chunk 242 of 297
Inserted chunk 243 of 297
Inserted chunk 244 of 297
Inserted chunk 245 of 297
Inserted chunk 246 of 297
Inserted chunk 247 of 297
Inserted chunk 248 of 297
Inserted chunk 249 of 297
Inserted chunk 250 of 297
Inserted chunk 251 of 297
Inserted chunk 252 of 297
Inserted chunk 253 of 297
Inserted chunk 254 of 297
Inserted chunk 255 of 297
Inserted chunk 256 of 297
Inserted chunk 257 of 297
Inserted chunk 258 of 297
Inserted chunk 259 of 297
Inserted chunk 260 of 297
Inserted chunk 261 of 297
Inserted chunk 262 of 297
Inserted chunk 263 of 297
Inserted chunk 264 of 297
Inserted chunk 265 of 297
Inserted chunk 266 of 297
Inserted chunk 267 of 297
Inserted chunk 268 of 297
Inserted chunk 269 of 297
Inserted chunk 270 of 297
Inserted chunk 271 of 297
Inserted chunk 272 of 297
Inserted chunk 273 of 297
Inserted chunk 274 of 297
Inserted chunk 275 of 297
Inserted chunk 276 of 297
Inserted chunk 277 of 297
Inserted chunk 278 of 297
Inserted chunk 279 of 297
Inserted chunk 280 of 297
Inserted chunk 281 of 297
Inserted chunk 282 of 297
Inserted chunk 283 of 297
Inserted chunk 284 of 297
Inserted chunk 285 of 297
Inserted chunk 286 of 297
Inserted chunk 287 of 297
Inserted chunk 288 of 297
Inserted chunk 289 of 297
Inserted chunk 290 of 297
Inserted chunk 291 of 297
Inserted chunk 292 of 297
Inserted chunk 293 of 297
Inserted chunk 294 of 297
Inserted chunk 295 of 297
Inserted chunk 296 of 297
Inserted chunk 297 of 297